<?php

/**
 * @file
 * Contains alipay.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function alipay_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alipay module.
    case 'help.page.alipay':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Best Drupal payment module for chinese.[D, include alipay and wechat.') . '</p>';
      return $output;

    default:
  }
}
