commerce_payment.commerce_payment_gateway.plugin.alipay:
  type: commerce_payment_gateway_configuration
  mapping:
    client_type:
      type: string
      label: 'Client type'
    app_id:
      type: string
      label: 'APP ID'
    app_private_key_path:
      type: string
      label: 'The app private key'
    alipay_public_key_path:
      type: string
      label: 'The alipay public key'
    app_cert_public_key_path:
      type: string
      label: 'The App Cert path'
    alipay_cert_public_key_path:
      type: string
      label: 'The Alipay cert path'
    alipay_root_cert_path:
      type: string
      label: 'The Alipay Root cert path'

account.account_transfer_gateway.plugin.alipay:
  type: mapping
  mapping:
    app_id:
      type: string
      label: 'APP ID'
    app_private_key_path:
      type: string
      label: 'The app private key'
    alipay_public_key_path:
      type: string
      label: 'The alipay public key'
